FAST-HEP/fast-carpenter

.requirements_dev.txt, .travis.yml, README.rst, docs/command_line.rst, docs/conf.py, docs/examples.rst, docs/philosophy.rst, docs/setup.rst, setup.py
Fixes many links, badges, config, etc to point to the new github repo and CI tooling
=> Updates for GitHub

.travis.yml, fast_carpenter/__init__.py, setup.cfg
Bad indentation in the travis-ci YAML deploy step seems to have caused it not to be able to run.  (Hopefully) this fixes that.
=> Fix bad indenting which broke travis

docs/conf.py
=> Fix docs `source` links

fast_carpenter/define/variables.py, fast_carpenter/expressions.py, fast_carpenter/version.py, setup.cfg, tests/define/test_variables.py, tests/test_expressions.py
* Adds support for a limited number of constants (nan, inf, pi and e) as per issue #21 
* Adds option to mask jagged arrays as per issue #59.
* Bumps patch version: v0.13.1
=> Improve variable definition features

fast_carpenter/define/variables.py, fast_carpenter/summary/binned_dataframe.py
Fix pickle issue from a namedtuple defined in a funtion, and swap to `count` not `size` for BinnedDataframes to help with issue #51.
=> Fix pickle and use counts not size

CHANGELOG.md, tests/selection/test_stage.py
Add a changelog to be manually maintained for now.
=> Add changelog

CHANGELOG.md, fast_carpenter/__main__.py
I added the version number from #74
=> Added the version to the CLI

fast_carpenter/define/reductions.py
=> Support for negative reduce

CHANGELOG.md, fast_carpenter/define/reductions.py, fast_carpenter/version.py, setup.cfg, tests/define/test_reductions.py
Following #81 this adds unit tests to check it behaves.
=> Add unit tests for negative JaggedNth

fast_carpenter/__main__.py
This should fix #84 
Let me know if you'd like me to edit it somehow!
=> Give "fast-carpenter" to fast-flow to use as the back-end (fixes #84)

README.rst
=> Add zenodo to README

CHANGELOG.md, fast_carpenter/expressions.py, tests/test_expressions.py
Fixes #95:
- updated attribute regex
- replacing all the DOTs
- added tests
Pattern test: http://regexr.com/4nm39
=> Fixed issue #95: Allow for nested branch names in expressions

CHANGELOG.md, fast_carpenter/summary/binning_config.py, tests/summary/test_binning_config.py
=> Raise exception when duplicate out names given to BinnedDataframe

CHANGELOG.md, fast_carpenter/define/reductions.py, tests/define/test_reductions.py
=> Handle JaggedNth reductions for ND jagged arrays

CHANGELOG.md, fast_carpenter/summary/binned_dataframe.py, fast_carpenter/version.py, setup.cfg, tests/summary/test_binned_dataframe.py
=> Fix explode method for string arrays

CHANGELOG.md, setup.py
Move from atsge 0.1.11 to 0.2.0 which fixes this issue: https://github.com/shane-breeze/atsge/issues/6
=> Upgrade atsge

CHANGELOG.md, fast_carpenter/summary/binned_dataframe.py, fast_carpenter/version.py, setup.cfg, tests/summary/test_binned_dataframe.py
=> Add option to weight data

CHANGELOG.md, setup.py
From 0.30.0 various pipelines have been failing so pin to the latest version that seemed to work
=> Pin alphatwirl

CHANGELOG.md, fast_carpenter/__main__.py, fast_carpenter/bookkeeping.py, setup.py
Creates a tarball containing various book-keeping information, including the processing sequence, the dataset config, and the environment used to produce the dataset.
=> Add first version of book-keeping code

CHANGELOG.md, fast_carpenter/tree_wrapper.py, fast_carpenter/version.py, setup.cfg, setup.py
* Update CHANGELOG
* Pin pandas version
=> Prep for release v0.19.1
