FAST-HEP/fast-carpenter

- fast_carpenter/__main__.py
- fast_carpenter/summary/binned_dataframe.py
Core atuproot functionality is moved into a separate function `run_carpenter(sequence, datasets, args)`, which returns the processing sequence. This allows fast_carpenter to be used inside other scripts/notebooks. 
args passed to `__main__(args)` function outside of the cli are now parsed.
> Changes to __main__ entry point

- fast_carpenter/summary/binned_dataframe.py
- fast_carpenter/summary/binning_config.py
- tests/summary/dummy_binning_descriptions.py
- tests/summary/test_binned_dataframe.py
Fixes #46 
Adds ability to specify binning dimension and binning as expressions. Can be used to avoid creating a `fast_carpenter.Define` stage for simple transformations
e.g
```yaml
histogram:
binning:
- {in: MET_px**2 + MET_py**2, out: met,  bins: {low: 0, high: 10**2, nbins: 100}}
```
> Use numexpr when defining binning

- fast_carpenter/summary/binned_dataframe.py
- fast_carpenter/summary/binning_config.py
- tests/summary/dummy_binning_descriptions.py
- tests/summary/test_binning_config.py
`fast_carpenter` can now save the output pandas data frame in multiple different file types at once. I tested the default case where `file_format` is not included in the users yaml config and `fast_carpenter` produced the normal `.csv` file. I tested the yaml code below:
```yaml
file_format:
- {type: '.csv', float_format: '%.17g'}
- {type: ".pkl.compress", compression: "gzip"}
- type: '.h5'
key: df
```
and it produced 3 different files correctly. I also tested this case:
```yaml
file_format: {type: '.csv', float_format: '%.17g'}
```
and it worked fine (this is the default if the user doesn't specify `file_format`. I also tested this:
```yaml
file_format: '.p'
```
and it generated the pickle file fine.
If this merges correctly then this closes #53
> Added ability to save pandas dataframe as different file types

- fast_carpenter/summary/binned_dataframe.py
- fast_carpenter/version.py
- setup.cfg
- tests/conftest.py
- tests/summary/test_binned_dataframe.py
Since #46 there's been an issue that if two variables exist where the second's name is also a substring of the first, and if someone tries to make a binned dataframe using the first, the system crashes.  The problem arose from how we selected which branches need to be considered for input to the binning stage.
This PR: 
* Solves the above problem
* Bumps the minor version
* Adds more unit tests
It may also be related to #51, @rob-tay.
> Fix problem when similar branch names exist

- fast_carpenter/masked_tree.py
- tests/selection/test_stage.py
- tests/test_masked_tree.py
It turned out issue #58 was actually caused by issue #25.  This PR fixes both of these.
It overrides the `array` and `arrays` methods of `uproot.tree` by providing `MaskedUprootTree` with corresponding methods.  It also adds unit tests for these new methods.
This is potentially a large change in that some analysis configurations may now break if they relied on this inconsistent behaviour.
> Make array(s) methods consistent for masked uproot trees

- CHANGELOG.md
- fast_carpenter/tree_wrapper.py
- fast_carpenter/version.py
- setup.cfg
- tests/test_tree_wrapper.py
The itervalues method of `tree_wrapper.WrappedTree` returned all branches in the original tree and all newly defined values.  If a variable with the same name was added to the tree, this could cause problems.  Now we only return the overwritten branch instead.
> Fix itervalues for overwritten branches

- CHANGELOG.md
- fast_carpenter/tree_wrapper.py
- fast_carpenter/version.py
- setup.cfg
- tests/summary/test_binned_dataframe.py
User defined jagged arrays were not correctly interpreted for uproot by the WrappedTree class.
This was a problem when converting these variables to a pandas dataframe, giving rise to issue #67, which this fixes.
> Fix interpretation of user-defined JaggedArrays 

- CHANGELOG.md
- fast_carpenter/version.py
- setup.cfg
- setup.py
This should fix the CI failures of #90 and those seen in the demo repo pipeline (e.g. https://gitlab.cern.ch/fast-hep/public/fast_cms_public_tutorial/-/jobs/5836339).
> Pin atuproot to a stable version

- CHANGELOG.md
- fast_carpenter/selection/stage.py
- fast_carpenter/summary/binned_dataframe.py
- tests/selection/test_stage.py
- tests/summary/test_binned_dataframe.py
Add in defaulted options to collector.collect()
- one to return data in-memory
- one to control file writing
Both are defaulted to expected behavior in fast-carpenter.
This is towards #88.
> Allow collectors to return data

- CHANGELOG.md
- fast_carpenter/summary/binned_dataframe.py
- tests/summary/test_binned_dataframe.py
A bug in the explode function for the BinnedDataframe stage was causing problems when events were empty and a non-float column was provided (e.g. bool).  This was raised as issue #89.  This PR fixes this issue.
> Fix issue 89

- CHANGELOG.md
- fast_carpenter/__main__.py
- fast_carpenter/version.py
- setup.cfg
Following PR #90, the command line interface prints a lot of information out at the end of the job.  This PR tidies this up.
> Tidy up final print after job

- fast_carpenter/__main__.py
AlphaTwirl doesn't pass back the results of the run if used with the profiling option causing a crash at the final step in the command-line tool.  This adds a simple protection for this case.
> Handle final printout when profiling

- CHANGELOG.md
- fast_carpenter/__main__.py
- fast_carpenter/backends/__init__.py
- fast_carpenter/backends/alphatwirl.py
- tests/backends/test_init.py
Refactors the code that interfaces with AlphaTwirl to be just one back-end.  In the process defines what the interface for other backends will look like.  Related to #88, as well.
> Make alphatwirl into the first generalised "backend"

- CHANGELOG.md
- fast_carpenter/__main__.py
- fast_carpenter/backends/__init__.py
- fast_carpenter/backends/coffea.py
- fast_carpenter/version.py
- setup.cfg
- tests/backends/test_init.py
- tests/summary/test_binned_dataframe.py
Adds a backend based on the interface defined from #101, that uses coffea's uproot executor, similar to AlphaTwirl's multiprocessing mode.  Related to issue #88.  Uses code originally written by @lgray in his snippet: https://gist.github.com/lgray/58cc92282168097efef9e2fab83f397a
> Add a coffea backend for local processing

- fast_carpenter/summary/eventByEvent_dataframe.py
This PR implements the first version of the event-by-event dataframe feature.
This is how one can use it:
1) Add stage to the yaml config file:
```
- test: fast_carpenter.EventByEventDataframe
```
2) Add the stage description, e.g.
```
unbinned:
collections: [HT, MHT_pt, CleanJet_pt, CleanJet_eta, CleanJet_phi]
```
3) Run using usual `fast-carpenter` commands.
4) Step 3 will yield an output df in hdf5 format, that you can read this way:
```
import pandas as pd
df = pd.read_hdf("df_unbinned.hd5")
```
It has this form:
```
dataset   entry  subentry  CleanJet_eta  CleanJet_phi  CleanJet_pt          HT      MHT_pt     hashed_filename
0       ZJetsToNuNu_HT-400To600       0         0      2.365234     -0.485901   371.718628  491.044373  358.940094 -306183991803814303
1 …
```
> Event by event dataframe

- CHANGELOG.md
- fast_carpenter/define/systematics.py
- fast_carpenter/version.py
- setup.cfg
- tests/define/test_systematics.py
This PR gives the SystematicWeights stage more functionality:
* User can now change the way the output weights are called with the `out_format` option
* User can give arbitrary variations now (not just nominal, up, and down) by giving the `extra_variations` a list of additional valid variations and then adding the necessary variation in the `weights` configuration.
* Complex weight formulae are now supported directly (before only multiplications were allowed).
> Improve SystematicWeights stage

- CHANGELOG.md
- fast_carpenter/summary/binned_dataframe.py
- fast_carpenter/summary/binning_config.py
- fast_carpenter/version.py
- setup.cfg
- tests/summary/dummy_binning_descriptions.py
- tests/summary/test_binned_dataframe.py
- tests/summary/test_binning_config.py
@vukasinmilosevic reported that bin contents were being reset to 0 when the `pad_missing` option was set to true.  
This comes down to a problem with `pandas.DataFrame.reindex` removing bins from the dataframe if they're not included in the list of bins that need to be added.   All bins were being included but with a change in the number of decimal places on the bin edges so that the new bins were not being equated.  I've fixed the problem with the bin contents being reset, but the result now is that the bin edges have many decimal places in the output CSV.  I'm not sure if this is solvable yet, if not I'll merge anyway.
> Fix pad_missing for bin edges with many decimal places

- CHANGELOG.md
- fast_carpenter/summary/binned_dataframe.py
- fast_carpenter/version.py
- setup.cfg
- setup.py
- tests/summary/test_binned_dataframe.py
When there are many bins in a binned dataframe producing all of them, even those that aren't actually filled, can consume a lot of memory and a lot more processing time.  This new option enables the resulting dataframe to be much more sparse by only filling bins with non-zero.  This can be combined with the `pad_missing` option that existed previously to force these bins to be added back in the merging step.
**Note** that in the future this option might be automatically enabled / disabled in conjunction with `pad_missing` since this is really a performance optimisation control that a user often may not want to have to know about.
> Add `observed` option for speed with many bins

- CHANGELOG.md
- fast_carpenter/expressions.py
- fast_carpenter/version.py
- setup.cfg
- setup.py
- tests/test_expressions.py
This PR adds the functionality of variable broadcasting before passing into numexpr.
This means we can now mix variables with different jaggedness more conveniently within expressions, with less need for external stages.
> Add variable broadcasting for expressions

- CHANGELOG.md
- fast_carpenter/__main__.py
- fast_carpenter/backends/__init__.py
- fast_carpenter/backends/coffea.py
This PR adds support for the Dask and Parsl executors in Coffea.  This is not a complete / final implementation, but a starting point for testing.
Notes:
* I have not yet tested the DASK executor since I am not easily set up with a Dask cluster anywhere
* The Parsl backend has an involved configuration mechanism.  I have therefore only hooked up the "local" version of this, with a limited set of configuration options.  I think this is a decent starting point, and one we can expand on demand / need.
> Extend coffea backend support

- CHANGELOG.md
- setup.py
Numba was included in setup.py as a dependency - but we dont use this, and it caused issues when building the documentation on readthedocs.
> Remove numba dependency

- fast_carpenter/bookkeeping.py
- fast_carpenter/define/variables.py
- fast_carpenter/event_builder.py
- fast_carpenter/expressions.py
- fast_carpenter/tree_wrapper.py
- setup.py
- tests/conftest.py
- tests/define/test_reductions.py
- tests/selection/test_filters.py
- tests/test_expressions.py
First part of getting this to work with uproot4 is fixing what is broken:
- renamed all `uproot` instances to `uproot3`
- renamed all `awkward` instances to `awkward0`
- removed Python 2 support
- added `uproot3` and `awkward0` to install requirements
Next: encapsulation of all uproot and awkward usage such that uproot4 can be used in parallel
> Issue 141 part 1: Making it work with uproot3

- fast_carpenter/__main__.py
- fast_carpenter/backends/__init__.py
- fast_carpenter/backends/_alphatwirl.py
- fast_carpenter/data_import/_uproot4.py
- fast_carpenter/tree_adapter.py
- fast_carpenter/version.py
- setup.py
- tests/backends/test_alphatwirl.py
Since coffea does not support multi-tree access (for now), need to add alphatwirl back until we have a better solution.
- added custom version of `BEvents`
- added plugins to `AtuprootContext`
> Bringing alphatwirl back (for now)
